### ISSUE TITLE
fix: back on singlepage goes to previous route not back to all products

### ISSUE THREAD

**Issue by parkerjgit** [PastaMaker-FS/PastaMaker#101]
behaving like a model and a page. need to pick. either model pops up in allproducts, or it should have a route so back works.

**Comment by crazyrabbitLTC** [comment]
Interesting! now I understand, when you click BACK button.

**Comment by crazyrabbitLTC** [comment]
I found a work around, I made the single product a true modal that hovers over all products, rather than conditionally renders. This should solve the User experience issue of a non-working "back" button.
