### ISSUE TITLE
prevent negative quantities

### ISSUE THREAD

**Issue by parkerjgit** [PastaMaker-FS/PastaMaker#77]

**Comment by crazyrabbitLTC** [comment]
I will add for validation. We can also add this to our sequelize model to prevent cory from using it as a backway to get a 'negative purchase price'

**Comment by crazyrabbitLTC** [comment]
(Validation in the Cart form I mean)

**Comment by crazyrabbitLTC** [comment]
Fixed. Will be pushing up soon. (Form validation only)
